// Generated by CoffeeScript 1.9.1
(function() {
  var fs;

  fs = require('fs');

  this.FileDB = (function() {
    var data;

    data = {};

    function FileDB(file_name, write_timeout) {
      this.file_name = file_name;
      this.write_timeout = write_timeout != null ? write_timeout : 1000;
      this.startWriteToFileTimer();
    }

    FileDB.prototype.setWriteToFileTimeout = function(write_timeout) {
      this.write_timeout = write_timeout;
      this.stopWriteToFileTimer();
      return this.startWriteToFileTimer();
    };

    FileDB.prototype.stopWriteToFileTimer = function() {
      if (this.interval_id) {
        return clearInterval(this.interval_id);
      }
    };

    FileDB.prototype.startWriteToFileTimer = function() {
      return this.interval_id = setInterval(((function(_this) {
        return function() {
          return _this.writeToFile();
        };
      })(this)), this.write_timeout);
    };

    FileDB.prototype.getData = function() {
      return this.data;
    };

    FileDB.prototype.writeToFile = function() {
      return fs.writeFile(this.file_name, JSON.stringify(data), function(err) {
        if (err) {
          return console.log(err);
        }
      });
    };

    return FileDB;

  })();

  module.exports = this.FileDB;

}).call(this);

//# sourceMappingURL=FileDB.js.map
