// Generated by CoffeeScript 1.9.1
(function() {
  var connection_color_letters, db, file_db, server, socket_io;

  socket_io = require('socket.io');

  db = require('./FileDB.js');

  file_db = new db('test', 2000);

  server = socket_io(8080);

  connection_color_letters = "123456789ABCDEF";

  server.on('connection', function(socket) {
    var connection_color, i, j;
    connection_color = '#';
    for (i = j = 0; j <= 6; i = ++j) {
      connection_color += connection_color_letters[Math.floor(Math.random() * connection_color_letters.length)];
    }
    console.log(connection_color);
    return socket.on('saveElement', function(hash, data) {
      return server.emit('updateElement', connection_color, hash, data);
    });
  });

}).call(this);

//# sourceMappingURL=index.js.map
